openapi: 3.0.0
info:
  title: Image Censoring API
  description: API for detecting and applying various censoring effects to sensitive areas in images
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /process:
    post:
      summary: Process an image with censoring effects
      description: Upload an image and apply selected censoring effects to detected sensitive areas
      operationId: processImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessImageRequest'
            example:
              image: "data:image/jpeg;base64,/9j/4AAQSkZJRg..."
              effect: "pixelation"
              enabled_parts: ["face", "eyes"]
              strength: 7
              sticker_category: "emoji"
      responses:
        '200':
          description: Image processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessImageResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /:
    get:
      summary: Health check endpoint
      description: Check if the API is running and healthy
      operationId: healthCheck
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-03-15T10:30:00Z"

components:
  schemas:
    ProcessImageRequest:
      type: object
      required:
        - image
      properties:
        image:
          type: string
          description: Base64 encoded image data with data URI scheme
        effect:
          type: string
          enum: [pixelation, blur, blackbox, ruin, sticker]
          default: pixelation
          description: Type of censoring effect to apply
        enabled_parts:
          type: array
          items:
            type: string
            enum:
              - face
              - eyes
              - mouth
              - exposed_breast_f
              - covered_breast_f
              - exposed_genitalia_f
              - covered_genitalia_f
              - exposed_breast_m
              - exposed_genitalia_m
              - exposed_buttocks
              - covered_buttocks
              - belly
              - feet
          description: List of body parts to detect and censor
        strength:
          type: integer
          minimum: 1
          maximum: 10
          default: 7
          description: Strength of the censoring effect (1-10)
        sticker_category:
          type: string
          description: Category of stickers to use (only for sticker effect)

    ProcessImageResponse:
      type: object
      required:
        - processed_image
        - regions
      properties:
        processed_image:
          type: string
          description: Base64 encoded processed image data
        regions:
          type: array
          items:
            $ref: '#/components/schemas/DetectedRegion'

    DetectedRegion:
      type: object
      required:
        - type
        - coords
      properties:
        type:
          type: string
          description: Type of detected region
        coords:
          type: array
          items:
            type: integer
          minItems: 4
          maxItems: 4
          description: Coordinates [x, y, width, height]
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Detection confidence score
        label:
          type: string
          description: Detailed label of the detected region
        detection_type:
          type: string
          description: Type of detection method used

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message describing what went wrong 